spring:
  application:
    name: warehouse-api

  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse_db
    username: dev_user
    password: EqaSgNA-m3v9ooDxfRit
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080